### ISSUE TITLE
Dependency "voxeet-ios-conferencekit" has no shared framework schemes

### ISSUE THREAD

**Issue by karthinalliyappan** [voxeet/voxeet-ios-conferencekit#2]
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwib7vv39MHeAhUY5o8KHaD3CJcQFjAAegQIAxAB&url=https%3A%2F%2Fgithub.com%2FCarthage%2FCarthage%2Fissues%2F2632&usg=AOvVaw0yvcHz8jfE_yUdj1P78b6d

**Comment by Comanga** [comment]
Hello,

Can you write a real message about your problem(s) instead of throwing some links like this?
The title and your link do not match, I need some explanations to help you.

Thank you.
